### ISSUE TITLE
site yarn install error

### ISSUE THREAD

**Issue by lesvere** [BroadleafCommerce/ReactStarter#26]
yarn version: 1.22.4
node --version: v10.21.0

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/vere/.develop/code/java/ReactStarter/site/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.19.0-9-amd64
gyp ERR! command "/usr/bin/node" "/home/vere/.develop/code/java/ReactStarter/site/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/vere/.develop/code/java/ReactStarter/site/node_modules/node-sass
gyp ERR! node -v v10.21.0
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok 
Build failed with error code: 1

**Comment by lesvere** [comment]
First stp npm i node-sass
Then to  run yarn install 
It works!

**Comment by lesvere** [comment]
It's resolved!
