### ISSUE TITLE
Yarn start error

### ISSUE THREAD

**Issue by chungchi300** [BroadleafCommerce/ReactStarter#31]
```
 node -r dotenv/config dist/server.js dotenv_config_path=config/production.env
/Users/jeffchung/work/ReactStarter/site/node_modules/babel-polyfill/node_modules/core-js/modules/_typed-buffer.js:157
  if(numberLength != byteLength)throw RangeError(WRONG_LENGTH);
                                ^

RangeError: Wrong length!
    at validateArrayBufferArguments (/Users/jeffchung/work/ReactStarter/site/node_modules/babel-polyfill/node_modules/core-js/modules/_typed-buffer.js:157:39)
    at new ArrayBuffer (/Users/jeffchung/work/ReactStarter/site/node_modules/babel-polyfill/node_modules/core-js/modules/_typed-buffer.js:247:29)
    at zlib.js:330:28
    at NativeModule.compile (internal/bootstrap/loaders.js:364:7)
    at Function.NativeModule.require (internal/bootstrap/loaders.js:176:18)
    at Function.Module._load (internal/modules/cjs/loader.js:572:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/jeffchung/work/ReactStarter/site/node_modules/express-http-proxy/app/steps/decorateUserRes.js:5:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by chungchi300** [comment]
tried
1. npm i node-sass 
2. yarn install
3. npm run development

still no luck
